### ISSUE TITLE
Weird resolving of config location

### ISSUE THREAD

**Issue by freeDom-** [mawinkler/uptonight#14]
Hi,

I encountered a weird behavior that could easily be changed, but caused me some headaches.
If working directory is ~/ and uptonight is installed in some other directory e.g. /opt/uptonight and config.yaml is also in /opt/uptonight ```python /opt/uptonight/main.py``` will fail to find the config.yaml.
Running ```cd /opt/uptonight && python main.py``` will find the config.yaml since it is then inside the current working directory.

Although there is a workaround, it is not very intuitive that the config file will be searched in the current working directory. Typically the directory of the program is used (and a config path can be set as parameter).

**Comment by freeDom-** [comment]
https://stackoverflow.com/questions/3430372/how-do-i-get-the-full-path-of-the-current-files-directory

Here is the solution of how to actually get the path of the script instead of the path of cwd.

**Comment by mawinkler** [comment]
Hi,

good find. This problem didn't occur to me since I run UpTonight containerized, but it makes perfect sense. I will fix it.

**Comment by mawinkler** [comment]
Fixed with release 1.5.
