### ISSUE TITLE
Only getting Plots for Planets

### ISSUE THREAD

**Issue by TheFett** [mawinkler/uptonight#15]
Recently re-deployed Uptonight to a new machine so using the same Compose file.  Now I'm only getting information and plots for Planets and not galaxies, nebula, etc...

 ✔ Container uptonight  Created                                                                                                                            0.0s 
Attaching to uptonight
uptonight  | /app
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Location longitude: -122d32m29.598s
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Location latitude: 47d11m17.502s
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Location elevation: 519
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Location timezone: America/Los_Angeles
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Environment pressure: 1.022
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Environment temperature: 18.0
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Environment relative_humidity: 0.7
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Altitude constraint min: 30
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Altitude constraint max: 80
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Airmass constraint: 2
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Size constraint min: 10
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Size constraint max: 300
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Moon separation min: 45
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Moon separation use illumination: True
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Fraction of time observable threshold: 0.5
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Max number within threshold: 60
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] North to East ccw: False
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Observation date: None
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Target list: targets/GaryImm
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Type filter: 
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Output directory: /app/out
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [main] Mode: False
uptonight  | 2024-09-17 14:47:35 INFO (MainThread) [main] UpTonight one-time calculation mode
uptonight  | 2024-09-17 14:47:35 DEBUG (MainThread) [_get_observer] Observer created
uptonight  | 2024-09-17 14:47:35 INFO (MainThread) [__init__] Calculating for: 09/17/2024 19:00:00
uptonight  | 2024-09-17 14:47:35 INFO (MainThread) [__init__] UTC offset: -7.0
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [__init__] Sun set astronomical: 09/18/2024 04:01:45
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [__init__] Sun rise astronomical: 09/18/2024 12:07:13
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [__init__] Moon illumination: 100%
uptonight  | 2024-09-17 14:47:37 DEBUG (MainThread) [_get_sun_moon] Sun and Moon helper created
uptonight  | 2024-09-17 14:47:37 DEBUG (MainThread) [_get_observation_timeframe] Observing start time: 09/18/2024 04:01:45
uptonight  | 2024-09-17 14:47:37 DEBUG (MainThread) [_get_constraints] Constraints applied
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [__init__] Building targets lists
uptonight  | 2024-09-17 14:47:37 DEBUG (MainThread) [input_targets_add_foto] Adding fraction of time observable to input targets
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [calc] Number of targets within constraints: 0
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [_bodies] Creating plot and table of bodies
uptonight  | 2024-09-17 14:47:37 INFO (MainThread) [_bodies] Moon is observable
uptonight  | 2024-09-17 14:47:38 INFO (MainThread) [_bodies] Mars is observable
uptonight  | 2024-09-17 14:47:38 INFO (MainThread) [_bodies] Jupiter is observable
uptonight  | 2024-09-17 14:47:39 INFO (MainThread) [_bodies] Saturn is observable
uptonight  | 2024-09-17 14:47:39 INFO (MainThread) [_bodies] Uranus is observable
uptonight  | 2024-09-17 14:47:39 INFO (MainThread) [_bodies] Neptune is observable
uptonight  | 2024-09-17 14:47:39 INFO (MainThread) [_bodies] Creating result table of bodies
uptonight  | 2024-09-17 14:47:39 DEBUG (MainThread) [_bodies] Calculating max altitude for Moon
uptonight  | 2024-09-17 14:47:39 DEBUG (MainThread) [_bodies] Calculating max altitude for Mars
uptonight  | 2024-09-17 14:47:40 DEBUG (MainThread) [_bodies] Calculating max altitude for Jupiter
uptonight  | 2024-09-17 14:47:40 DEBUG (MainThread) [_bodies] Calculating max altitude for Saturn
uptonight  | 2024-09-17 14:47:40 DEBUG (MainThread) [_bodies] Calculating max altitude for Uranus
uptonight  | 2024-09-17 14:47:40 DEBUG (MainThread) [_bodies] Calculating max altitude for Neptune
uptonight  | 2024-09-17 14:47:40 DEBUG (MainThread) [calc] Saving plot
uptonight  | 2024-09-17 14:47:41 DEBUG (MainThread) [calc] Saving reports
uptonight  | target name hmsdms right ascension declination ... constellation size mag foto
uptonight  | ----------- ------ --------------- ----------- ... ------------- ---- --- ----
uptonight  | target name                 hmsdms                 ...  type  foto
uptonight  | ----------- -------------------------------------- ... ------ ----
uptonight  |     Neptune   23h55m40.07229124s -01d54m52.226644s ... Planet  1.0
uptonight  |      Saturn 23h07m49.76512523s -07d58m20.68712188s ... Planet  1.0
uptonight  |      Uranus 03h38m14.40938183s +19d10m41.72141726s ... Planet  0.9
uptonight  |     Jupiter 05h17m57.20592768s +22d22m28.26789774s ... Planet  0.8
uptonight  |        Mars 06h33m29.06932086s +23d27m44.71325538s ... Planet  0.6
uptonight  |        Moon 00h05m46.55686211s +00d07m54.87021548s ...   Moon  0.6
uptonight  | 2024-09-17 14:47:45 INFO (MainThread) [main] Execution time: 10.442051649093628 seconds

**Comment by mawinkler** [comment]
Hi,
if you're using _my_ `mawinkler/uptonight` image it could be, that this was broken. I pushed it again and verified that it's working. So do a pull and test again.

**Comment by TheFett** [comment]
Thanks.  I pulled the latest, but still only getting Solar System Bodies:

docker pull mawinkler/uptonight
Using default tag: latest
latest: Pulling from mawinkler/uptonight
Digest: sha256:ea2aa2756ac56012ab5ff059c308921c40ff9031419a84b1a0955ac754aa25ae
Status: Image is up to date for mawinkler/uptonight:latest
docker.io/mawinkler/uptonight:latest

 ✔ Container uptonight  Recreated                                                                                                                          2.7s 
Attaching to uptonight
uptonight  | /app
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Location longitude: -122d32m29.598s
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Location latitude: 47d11m17.502s
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Location elevation: 519
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Location timezone: America/Los_Angeles
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Environment pressure: 1.022
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Environment temperature: 18.0
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Environment relative_humidity: 0.7
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Altitude constraint min: 30
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Altitude constraint max: 80
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Airmass constraint: 2
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Size constraint min: 10
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Size constraint max: 300
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Moon separation min: 45
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Moon separation use illumination: True
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Fraction of time observable threshold: 0.5
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Max number within threshold: 60
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] North to East ccw: False
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Observation date: None
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Target list: /app/targets/GaryImm
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Type filter: 
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Output directory: /app/out
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [main] Mode: False
uptonight  | 2024-09-17 16:29:58 INFO (MainThread) [main] UpTonight one-time calculation mode
uptonight  | 2024-09-17 16:29:58 DEBUG (MainThread) [_get_observer] Observer created
uptonight  | 2024-09-17 16:29:58 INFO (MainThread) [__init__] Calculating for: 09/17/2024 19:00:00
uptonight  | 2024-09-17 16:29:58 INFO (MainThread) [__init__] UTC offset: -7.0
uptonight  | 2024-09-17 16:30:12 INFO (MainThread) [__init__] Sun set astronomical: 09/18/2024 04:01:45
uptonight  | 2024-09-17 16:30:12 INFO (MainThread) [__init__] Sun rise astronomical: 09/18/2024 12:07:13
uptonight  | 2024-09-17 16:30:12 INFO (MainThread) [__init__] Moon illumination: 100%
uptonight  | 2024-09-17 16:30:12 DEBUG (MainThread) [_get_sun_moon] Sun and Moon helper created
uptonight  | 2024-09-17 16:30:12 DEBUG (MainThread) [_get_observation_timeframe] Observing start time: 09/18/2024 04:01:45
uptonight  | 2024-09-17 16:30:12 DEBUG (MainThread) [_get_constraints] Constraints applied
uptonight  | 2024-09-17 16:30:12 INFO (MainThread) [__init__] Building targets lists
uptonight  | 2024-09-17 16:30:13 DEBUG (MainThread) [input_targets_add_foto] Adding fraction of time observable to input targets
uptonight  | 2024-09-17 16:30:13 INFO (MainThread) [calc] Number of targets within constraints: 0
uptonight  | 2024-09-17 16:30:13 INFO (MainThread) [_bodies] Creating plot and table of bodies
uptonight  | 2024-09-17 16:30:13 INFO (MainThread) [_bodies] Moon is observable
uptonight  | 2024-09-17 16:30:14 INFO (MainThread) [_bodies] Mars is observable
uptonight  | 2024-09-17 16:30:14 INFO (MainThread) [_bodies] Jupiter is observable
uptonight  | 2024-09-17 16:30:14 INFO (MainThread) [_bodies] Saturn is observable
uptonight  | 2024-09-17 16:30:15 INFO (MainThread) [_bodies] Uranus is observable
uptonight  | 2024-09-17 16:30:15 INFO (MainThread) [_bodies] Neptune is observable
uptonight  | 2024-09-17 16:30:15 INFO (MainThread) [_bodies] Creating result table of bodies
uptonight  | 2024-09-17 16:30:15 DEBUG (MainThread) [_bodies] Calculating max altitude for Moon
uptonight  | 2024-09-17 16:30:15 DEBUG (MainThread) [_bodies] Calculating max altitude for Mars
uptonight  | 2024-09-17 16:30:15 DEBUG (MainThread) [_bodies] Calculating max altitude for Jupiter
uptonight  | 2024-09-17 16:30:15 DEBUG (MainThread) [_bodies] Calculating max altitude for Saturn
uptonight  | 2024-09-17 16:30:16 DEBUG (MainThread) [_bodies] Calculating max altitude for Uranus
uptonight  | 2024-09-17 16:30:16 DEBUG (MainThread) [_bodies] Calculating max altitude for Neptune
uptonight  | 2024-09-17 16:30:16 DEBUG (MainThread) [calc] Saving plot
uptonight  | 2024-09-17 16:30:17 DEBUG (MainThread) [calc] Saving reports
uptonight  | target name hmsdms right ascension declination ... constellation size mag foto
uptonight  | ----------- ------ --------------- ----------- ... ------------- ---- --- ----
uptonight  | target name                 hmsdms                 ...  type  foto
uptonight  | ----------- -------------------------------------- ... ------ ----
uptonight  |     Neptune   23h55m40.07229124s -01d54m52.226644s ... Planet  1.0
uptonight  |      Saturn 23h07m49.76512523s -07d58m20.68712188s ... Planet  1.0
uptonight  |      Uranus 03h38m14.40938183s +19d10m41.72141726s ... Planet  0.9
uptonight  |     Jupiter 05h17m57.20592768s +22d22m28.26789774s ... Planet  0.8
uptonight  |        Mars 06h33m29.06932086s +23d27m44.71325538s ... Planet  0.6
uptonight  |        Moon 00h05m46.55686211s +00d07m54.87021548s ...   Moon  0.6
uptonight  | 2024-09-17 16:30:18 INFO (MainThread) [main] Execution time: 19.785048246383667 seconds
uptonight exited with code 0

**Comment by mawinkler** [comment]
I don't know your configuration, but what happens if you only set your longitude and latitude (and leave all the rest as default)?

**Comment by mawinkler** [comment]
If your last variant is what you're using, then there are the indentations missing. Compare with the README.
Your local path should point to the `www` directory not the base dir of home assistant.
Other than that I don't know, it's working as expected on my side with the current latest.

**Comment by mawinkler** [comment]
Try to set

```
constraints:
    moon_separation_min: 45  # in degrees
    moon_separation_use_illumination: false
```

My guess is, that due to full moon there are no DSOs within the constraints

**Comment by TheFett** [comment]
Thanks. I thought about that, but been away and haven’t had a chance to work with itI’ll get back to you. Again, thanks for looking into it. On Sep 19, 2024, at 8:56 AM, Markus Winkler ***@***.***> wrote:﻿
Try to set
constraints:
    moon_separation_min: 45  # in degrees
    moon_separation_use_illumination: false

My guess is, that due to full moon there are no DSOs within the constraints

**Comment by TheFett** [comment]
Sorry for the delay, it was the moon illumination that was causing the issue.  Thanks for the help, this issue is resolved.
