### ISSUE TITLE
Home Assistant integration

### ISSUE THREAD

**Issue by NavidHeisenberg** [mawinkler/uptonight#6]
Hi, Love your code! I noticed you integrated the code into Home Assistant via JSON. Can you elaborate please? How do you pull the graph/report to HA?

**Comment by xstrex** [comment]
Just an idea, but why not add the uptonight docker container to the official add-on store, or at least as a custom repository? 
https://developers.home-assistant.io/docs/add-ons/ 

After all, HAOS just runs home-assistant as a docker container, as well as other add-ons. https://www.home-assistant.io/addons/
